import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { convertContactsToPhoneBook } from '~/utils';

const initialState = {
    phoneBook: {},
    loading: false,
};

// TODO fetch data
const getPhoneBook = createAsyncThunk('phoneBook/getPhoneBook', () => [
    {
        name: 'Sean Gerlach',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Miss Elijah Conroy',
        isFriend: false,
        isSentRequest: true,
        id: '1',
    },
    {
        name: 'Kelly Nitzsche',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Terence Koss',
        isFriend: true,
        isSentRequest: true,
        id: '2',
    },
    {
        name: 'Olivia Cormier',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Miss Georgia Koch',
        isFriend: false,
        isSentRequest: false,
        id: '3',
    },
    {
        name: 'June Padberg',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Mercedes Nienow',
        isFriend: true,
        isSentRequest: false,
        id: '4',
    },
    {
        name: 'Miss Isabel Vandervort',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Alfred Wolff',
        isFriend: true,
        isSentRequest: true,
        id: '5',
    },
    {
        name: 'Beatrice Jast',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Kristina Spinka',
        isFriend: false,
        isSentRequest: false,
        id: '6',
    },
    {
        name: 'Raquel Jacobson',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Flora Johns',
        isFriend: false,
        isSentRequest: true,
        id: '7',
    },
    {
        name: 'Felipe Kreiger',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Jeannette Senger',
        isFriend: false,
        isSentRequest: false,
        id: '8',
    },
    {
        name: 'Thelma Swift',
        avatar: 'https://loremflickr.com/640/480',
        alias: "Janie O'Reilly",
        isFriend: true,
        isSentRequest: true,
        id: '9',
    },
    {
        name: 'Wendell Anderson',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Chad Labadie',
        isFriend: true,
        isSentRequest: false,
        id: '10',
    },
    {
        name: 'Harold Ernser',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Dorothy Lakin',
        isFriend: true,
        isSentRequest: false,
        id: '11',
    },
    {
        name: 'Joyce Reichel',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Tasha Watsica',
        isFriend: true,
        isSentRequest: false,
        id: '12',
    },
    {
        name: 'Francisco Schuster',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Miguel Stracke V',
        isFriend: false,
        isSentRequest: true,
        id: '13',
    },
    {
        name: 'Mr. Fredrick McGlynn',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Miss Allen Wunsch',
        isFriend: true,
        isSentRequest: true,
        id: '14',
    },
    {
        name: 'Mr. Nicholas Leffler',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Mr. Jackie Little',
        isFriend: true,
        isSentRequest: false,
        id: '15',
    },
    {
        name: 'Mr. Sandra Halvorson',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Ada Runolfsdottir',
        isFriend: false,
        isSentRequest: false,
        id: '16',
    },
    {
        name: 'Kurt Feil',
        avatar: 'https://loremflickr.com/640/480',
        alias: "Diana O'Hara",
        isFriend: true,
        isSentRequest: true,
        id: '17',
    },
    {
        name: 'Shannon Haley',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Mr. Grace Fisher',
        isFriend: true,
        isSentRequest: false,
        id: '18',
    },
    {
        name: 'Bernadette Bernhard',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Marlon Bernhard PhD',
        isFriend: false,
        isSentRequest: true,
        id: '19',
    },
    {
        name: 'Mrs. Robert Torphy',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Marie Swaniawski',
        isFriend: true,
        isSentRequest: true,
        id: '20',
    },
    {
        name: 'Miss Jackie Rippin',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Ed Mosciski',
        isFriend: false,
        isSentRequest: false,
        id: '21',
    },
    {
        name: 'Mrs. Emmett McGlynn',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Willie Walter',
        isFriend: false,
        isSentRequest: false,
        id: '22',
    },
    {
        name: 'Ms. Lynn Crooks',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Miss Stuart Braun',
        isFriend: true,
        isSentRequest: false,
        id: '23',
    },
    {
        name: 'Gladys Dach',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Carlos Kuhn I',
        isFriend: false,
        isSentRequest: false,
        id: '24',
    },
    {
        name: 'Brandi Hartmann III',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Mrs. Ronald Macejkovic',
        isFriend: true,
        isSentRequest: true,
        id: '25',
    },
    {
        name: 'Lora Braun',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Leland Mayer',
        isFriend: true,
        isSentRequest: true,
        id: '26',
    },
    {
        name: 'Lewis Greenfelder',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Gina Jaskolski',
        isFriend: false,
        isSentRequest: false,
        id: '27',
    },
    {
        name: 'Marshall Okuneva',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Gladys Okuneva II',
        isFriend: false,
        isSentRequest: true,
        id: '28',
    },
    {
        name: 'Jeannette Hegmann',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Alberta Christiansen',
        isFriend: false,
        isSentRequest: false,
        id: '29',
    },
    {
        name: 'Virginia Haley',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Camille Konopelski',
        isFriend: true,
        isSentRequest: false,
        id: '30',
    },
    {
        name: 'Victoria Bailey III',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Domingo Sipes',
        isFriend: false,
        isSentRequest: true,
        id: '31',
    },
    {
        name: 'Paulette Huel',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Miss Francisco Dietrich',
        isFriend: true,
        isSentRequest: true,
        id: '32',
    },
    {
        name: 'Sara Ferry',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Sean Kerluke',
        isFriend: true,
        isSentRequest: true,
        id: '33',
    },
    {
        name: 'Jeremiah Lang',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Rosemary Williamson',
        isFriend: true,
        isSentRequest: false,
        id: '34',
    },
    {
        name: "Wayne O'Keefe",
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Chad McKenzie',
        isFriend: false,
        isSentRequest: false,
        id: '35',
    },
    {
        name: 'Kelvin Ernser',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Natasha Fritsch',
        isFriend: false,
        isSentRequest: true,
        id: '36',
    },
    {
        name: 'Georgia Emard',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Homer Volkman',
        isFriend: true,
        isSentRequest: true,
        id: '37',
    },
    {
        name: 'Julia Orn Sr.',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Lorena Leffler',
        isFriend: false,
        isSentRequest: true,
        id: '38',
    },
    {
        name: 'Marta Walker',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Bethany Casper II',
        isFriend: true,
        isSentRequest: false,
        id: '39',
    },
    {
        name: 'Derrick Goyette',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Patty Hills',
        isFriend: false,
        isSentRequest: true,
        id: '40',
    },
    {
        name: 'Cecilia Keebler',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Shari Fahey',
        isFriend: false,
        isSentRequest: false,
        id: '41',
    },
    {
        name: 'Ryan Hagenes',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Gregg Hamill IV',
        isFriend: false,
        isSentRequest: true,
        id: '42',
    },
    {
        name: 'Ms. Corey Towne',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Vernon Fritsch',
        isFriend: false,
        isSentRequest: false,
        id: '43',
    },
    {
        name: 'Cathy Schimmel',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Everett Hilll',
        isFriend: true,
        isSentRequest: false,
        id: '44',
    },
    {
        name: 'Ellis Sipes Sr.',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Olivia Green',
        isFriend: true,
        isSentRequest: true,
        id: '45',
    },
    {
        name: 'Valerie Brekke V',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Hazel Cassin',
        isFriend: true,
        isSentRequest: false,
        id: '46',
    },
    {
        name: 'Jared Stiedemann DVM',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Rita Ankunding DVM',
        isFriend: true,
        isSentRequest: false,
        id: '47',
    },
    {
        name: 'Emanuel Cassin',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Beth Greenholt',
        isFriend: false,
        isSentRequest: true,
        id: '48',
    },
    {
        name: 'Miss Robin Roberts',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Dennis Grant',
        isFriend: false,
        isSentRequest: false,
        id: '49',
    },
    {
        name: 'Steven Keeling',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Ed Heidenreich II',
        isFriend: true,
        isSentRequest: true,
        id: '50',
    },
    {
        name: 'Pedro Zulauf',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Faith Aufderhar',
        isFriend: false,
        isSentRequest: false,
        id: '51',
    },
    {
        name: 'Omar Boehm',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Dr. Silvia Barrows',
        isFriend: false,
        isSentRequest: true,
        id: '52',
    },
    {
        name: 'Rickey McClure',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Sally Schmeler',
        isFriend: false,
        isSentRequest: true,
        id: '53',
    },
    {
        name: 'Pedro Auer',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Jonathan Haley',
        isFriend: false,
        isSentRequest: false,
        id: '54',
    },
    {
        name: 'Jerome Feest',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Taylor Hickle',
        isFriend: true,
        isSentRequest: true,
        id: '55',
    },
    {
        name: 'Silvia Torphy',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Vernon Metz',
        isFriend: false,
        isSentRequest: true,
        id: '56',
    },
    {
        name: 'Mrs. Melissa Effertz',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Leon Barrows',
        isFriend: false,
        isSentRequest: false,
        id: '57',
    },
    {
        name: 'Jean Hermann',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Andres Nienow DVM',
        isFriend: true,
        isSentRequest: true,
        id: '58',
    },
    {
        name: 'Armando Hansen',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Erma Batz Jr.',
        isFriend: false,
        isSentRequest: true,
        id: '59',
    },
    {
        name: 'Fred Hayes',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Mr. Janice Batz',
        isFriend: true,
        isSentRequest: true,
        id: '60',
    },
    {
        name: 'Dr. Dexter Dietrich',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Adrienne Ankunding',
        isFriend: false,
        isSentRequest: true,
        id: '61',
    },
    {
        name: 'Wilfred Paucek',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Jerome Kohler MD',
        isFriend: false,
        isSentRequest: false,
        id: '62',
    },
    {
        name: 'Rex Mante',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Miss Erik Greenholt',
        isFriend: true,
        isSentRequest: false,
        id: '63',
    },
    {
        name: 'Aubrey Ferry',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Ralph Shanahan',
        isFriend: false,
        isSentRequest: false,
        id: '64',
    },
    {
        name: 'Kathryn Davis',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Owen Murray DDS',
        isFriend: true,
        isSentRequest: false,
        id: '65',
    },
    {
        name: 'Dr. Marcella Corwin',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Ian Murphy',
        isFriend: true,
        isSentRequest: true,
        id: '66',
    },
    {
        name: 'Garry Lowe',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Antonia Olson',
        isFriend: true,
        isSentRequest: true,
        id: '67',
    },
    {
        name: 'Melissa Boehm',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Herman Hammes',
        isFriend: false,
        isSentRequest: true,
        id: '68',
    },
    {
        name: 'Mrs. Lorenzo Quitzon',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Janis Gleason V',
        isFriend: false,
        isSentRequest: true,
        id: '69',
    },
    {
        name: 'Lillian Zemlak',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Miss Rene Emmerich',
        isFriend: false,
        isSentRequest: true,
        id: '70',
    },
    {
        name: 'Nadine Prohaska',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Miss Richard Herman',
        isFriend: false,
        isSentRequest: true,
        id: '71',
    },
    {
        name: 'Samantha Braun II',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Clifford Ward',
        isFriend: false,
        isSentRequest: true,
        id: '72',
    },
    {
        name: 'Eunice Kohler',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Melissa Leuschke',
        isFriend: false,
        isSentRequest: true,
        id: '73',
    },
    {
        name: 'Gretchen Wunsch',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Shannon Steuber',
        isFriend: false,
        isSentRequest: false,
        id: '74',
    },
    {
        name: 'Bradford MacGyver',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Tommy Deckow',
        isFriend: false,
        isSentRequest: true,
        id: '75',
    },
    {
        name: 'Traci Hettinger',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Shirley Bashirian',
        isFriend: false,
        isSentRequest: false,
        id: '76',
    },
    {
        name: "Christian O'Reilly",
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Mary Murazik',
        isFriend: true,
        isSentRequest: true,
        id: '77',
    },
    {
        name: 'Brandon Luettgen',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Barry Doyle',
        isFriend: false,
        isSentRequest: true,
        id: '78',
    },
    {
        name: 'Camille Lesch',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Karen Marquardt',
        isFriend: true,
        isSentRequest: false,
        id: '79',
    },
    {
        name: 'Krista Beer',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Angel Crona',
        isFriend: true,
        isSentRequest: true,
        id: '80',
    },
    {
        name: 'Tracey Keebler',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Shari Weber',
        isFriend: true,
        isSentRequest: false,
        id: '81',
    },
    {
        name: 'Nora Balistreri',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Jane Rolfson',
        isFriend: false,
        isSentRequest: true,
        id: '82',
    },
    {
        name: 'Maria Mitchell',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Maureen Bergnaum',
        isFriend: false,
        isSentRequest: false,
        id: '83',
    },
    {
        name: 'Derrick Ernser',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Claude Casper',
        isFriend: false,
        isSentRequest: false,
        id: '84',
    },
    {
        name: 'Geraldine Jaskolski',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Alma Wolff',
        isFriend: true,
        isSentRequest: false,
        id: '85',
    },
    {
        name: 'Owen McClure',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Barbara Abshire',
        isFriend: false,
        isSentRequest: true,
        id: '86',
    },
    {
        name: 'Edith Krajcik',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Anita Heathcote',
        isFriend: true,
        isSentRequest: false,
        id: '87',
    },
    {
        name: 'Carlton Littel',
        avatar: 'https://loremflickr.com/640/480',
        alias: 'Cynthia Oberbrunner',
        isFriend: true,
        isSentRequest: false,
        id: '88',
    },
]);

const phoneBookSlice = createSlice({
    name: 'phoneBook',
    initialState,
    reducers: {
        updateContact: (state, { payload }) => {
            const firstCharOfName = (payload.alias || payload.name)[0].toUpperCase();
            const contacts = state.phoneBook[firstCharOfName];
            const index = contacts.findIndex((contact) => contact.id === payload.id);

            contacts[index] = payload;
        },
        recall: (state, { payload }) => {
            const firstCharOfName = (payload.alias || payload.name)[0].toUpperCase();
            const contacts = state.phoneBook[firstCharOfName];
            const index = contacts.findIndex((contact) => contact.id === payload.id);

            contacts[index].isSentRequest = false;
        },
    },
    extraReducers: (builder) => {
        builder
            .addCase(getPhoneBook.pending, (state) => {
                state.loading = true;
            })
            .addCase(getPhoneBook.rejected, (state) => {
                state.loading = false;
            })
            .addCase(getPhoneBook.fulfilled, (state, { payload }) => {
                state.loading = false;
                state.phoneBook = convertContactsToPhoneBook(payload);
            });
    },
});

export default phoneBookSlice.reducer;
export const { updateContact, recall } = phoneBookSlice.actions;
export { getPhoneBook };
