import { createSlice } from '@reduxjs/toolkit';
import { convertContactsToPhoneBook } from '~/utils';

const initialState = {
    phoneBook: convertContactsToPhoneBook([
        {
            name: 'Harvey Crona V',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Jonathon Flatley',
            id: '1',
        },
        {
            name: 'Fredrick Carroll',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Angela Gutkowski',
            id: '2',
        },
        {
            name: 'Diane Bechtelar',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Vera Hansen',
            id: '3',
        },
        {
            name: 'Helen VonRueden III',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Wendy Johns',
            id: '4',
        },
        {
            name: 'Desiree McDermott',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Opal Jast',
            id: '5',
        },
        {
            name: 'Miss Rhonda Collins',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Ricky Abbott',
            id: '6',
        },
        {
            name: 'Edgar Jones',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Luz Hoeger',
            id: '7',
        },
        {
            name: 'Jason Muller',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Paula Boehm II',
            id: '8',
        },
        {
            name: 'Robyn Walsh',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Mr. Marlon Sporer',
            id: '9',
        },
        {
            name: 'Marshall Johns',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Julie Hettinger',
            id: '10',
        },
        {
            name: 'Dwayne Gutkowski',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Dexter Wiegand',
            id: '11',
        },
        {
            name: 'Kara Hyatt PhD',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Mr. Jose Flatley DVM',
            id: '12',
        },
        {
            name: 'Drew Gleason',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: "Alejandro O'Keefe",
            id: '13',
        },
        {
            name: 'Sherry Boyle',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Miss Warren Mohr',
            id: '14',
        },
        {
            name: 'Lillian Bogisich Sr.',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Mr. Shirley Schoen',
            id: '15',
        },
        {
            name: 'Bennie Schuster IV',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Brenda Feest PhD',
            id: '16',
        },
        {
            name: 'Della Cummings',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Eunice Grant',
            id: '17',
        },
        {
            name: 'Bill Crona',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Chris Lang',
            id: '18',
        },
        {
            name: 'Lloyd Murray',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Beth Rogahn',
            id: '19',
        },
        {
            name: 'Herbert Hahn',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Belinda Leuschke PhD',
            id: '20',
        },
        {
            name: 'Ellis Larson',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Benny Anderson',
            id: '21',
        },
        {
            name: 'Marcus Stroman',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Ted Schuppe',
            id: '22',
        },
        {
            name: 'Patsy Langworth',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Belinda Bailey PhD',
            id: '23',
        },
        {
            name: 'Betsy Strosin',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Brooke Turcotte',
            id: '24',
        },
        {
            name: 'Blake Terry',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Lynda Botsford',
            id: '25',
        },
        {
            name: 'Aaron Hilpert',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Antonio Adams',
            id: '26',
        },
        {
            name: 'Ana Sauer',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Mrs. Bethany Russel',
            id: '27',
        },
        {
            name: 'Shaun Bins',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Kristopher Macejkovic III',
            id: '28',
        },
        {
            name: 'Miss Hector Jenkins',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Lillie Pfeffer',
            id: '29',
        },
        {
            name: 'Elmer McCullough',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Brian Hermiston',
            id: '30',
        },
        {
            name: 'Tom Hessel',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Craig Torp',
            id: '31',
        },
        {
            name: 'Mr. Claude Auer',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Cedric Quigley',
            id: '32',
        },
        {
            name: 'Miss Jack Yundt',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Toby Boyle',
            id: '33',
        },
        {
            name: 'Dr. Kayla Beahan',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Dr. Kathryn Sipes',
            id: '34',
        },
        {
            name: 'Jacqueline Rempel',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Robyn Marks IV',
            id: '35',
        },
        {
            name: 'Lucille Roberts IV',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Mabel Jaskolski',
            id: '36',
        },
        {
            name: 'Anna Lind',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Walter Doyle',
            id: '37',
        },
        {
            name: 'Mrs. Tracey Lockman',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Mr. Faith Sporer',
            id: '38',
        },
        {
            name: 'Whitney Jaskolski',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Kate Labadie',
            id: '39',
        },
        {
            name: 'Dr. Cecil Rolfson',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Pauline Mitchell DVM',
            id: '40',
        },
        {
            name: 'Geraldine Herman',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Christie Glover',
            id: '41',
        },
        {
            name: 'Linda Dicki',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Candice Schaefer',
            id: '42',
        },
        {
            name: 'Spencer Kuhic',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Ruben Baumbach MD',
            id: '43',
        },
        {
            name: 'Catherine Krajcik',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Dr. Nadine Zboncak',
            id: '44',
        },
        {
            name: 'Cecilia Kuphal DVM',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Benjamin Crooks',
            id: '45',
        },
        {
            name: 'Dr. Lillian Wunsch',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Opal Runolfsson',
            id: '46',
        },
        {
            name: 'Jackie Abshire DDS',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Lewis Marquardt III',
            id: '47',
        },
        {
            name: 'Brian Pacocha',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Otis Leffler',
            id: '48',
        },
        {
            name: 'Mrs. Alan Rutherford',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Claude Wisoky',
            id: '49',
        },
        {
            name: 'Miss Jan Lueilwitz',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Chad Lakin',
            id: '50',
        },
        {
            name: 'Annie Miller',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Freddie Hessel',
            id: '51',
        },
        {
            name: 'Wendy Blanda',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Johnnie Effertz',
            id: '52',
        },
        {
            name: 'Theodore Bailey',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Calvin Lockman',
            id: '53',
        },
        {
            name: 'Christy Weber',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Scott Pfannerstill Sr.',
            id: '54',
        },
        {
            name: 'Travis Vandervort',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Tabitha Gutkowski',
            id: '55',
        },
        {
            name: 'Iris Runte',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Dana Predovic',
            id: '56',
        },
        {
            name: 'Eduardo Krajcik',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Olive Kulas',
            id: '57',
        },
        {
            name: 'Sophia Jones',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Roy Smith',
            id: '58',
        },
        {
            name: 'Seth Hegmann',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Maxine Borer V',
            id: '59',
        },
        {
            name: 'Dr. Faye Zemlak',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Grady Herman',
            id: '60',
        },
        {
            name: 'Johnny Bauch',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Ron Boyer',
            id: '61',
        },
        {
            name: 'Ryan Hayes',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Darrell Morar',
            id: '62',
        },
        {
            name: 'Mrs. Jesus Farrell',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Leslie Tremblay Jr.',
            id: '63',
        },
        {
            name: 'Gary Hintz',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Ms. Nettie Russel',
            id: '64',
        },
        {
            name: 'Santos Prohaska',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Woodrow White',
            id: '65',
        },
        {
            name: 'Laurie Gleason',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Dawn Haley DDS',
            id: '66',
        },
        {
            name: 'Mrs. Ryan Schumm',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Edmond Wehner',
            id: '67',
        },
        {
            name: 'Hattie Lockman',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Keith Schoen',
            id: '68',
        },
        {
            name: "Laura O'Hara",
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Terence Steuber I',
            id: '69',
        },
        {
            name: 'Wayne Kiehn',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Cathy Hartmann',
            id: '70',
        },
        {
            name: 'Mathew Baumbach',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Marcia Kub',
            id: '71',
        },
        {
            name: 'Lori Padberg III',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Colin Mayer',
            id: '72',
        },
        {
            name: 'Barry Aufderhar',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Mrs. Rosalie Lindgren',
            id: '73',
        },
        {
            name: 'Mrs. Ethel Hackett',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Cecilia Metz',
            id: '74',
        },
        {
            name: 'Lucas Shanahan',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Jack Marvin',
            id: '75',
        },
        {
            name: 'Mrs. Johnathan Hyatt',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Laverne Ullrich',
            id: '76',
        },
        {
            name: 'Leah Mante',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Jordan Emmerich',
            id: '77',
        },
        {
            name: 'Grady Kihn',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Lora Bechtelar',
            id: '78',
        },
        {
            name: 'Elias Hammes',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Christopher Tremblay DDS',
            id: '79',
        },
        {
            name: 'Tommy Carter',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Delia McClure',
            id: '80',
        },
        {
            name: 'Aubrey Moen',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Silvia Beatty',
            id: '81',
        },
        {
            name: 'Ralph Borer',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Tommy Rempel DVM',
            id: '82',
        },
        {
            name: 'Jerome Skiles',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Douglas Hyatt',
            id: '83',
        },
        {
            name: 'Joe Batz',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Preston Grimes',
            id: '84',
        },
        {
            name: 'Conrad Dietrich',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Helen Balistreri II',
            id: '85',
        },
        {
            name: 'Olive Abernathy',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Bobbie Prohaska',
            id: '86',
        },
        {
            name: 'Dr. Katherine Stanton',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Stewart Murray',
            id: '87',
        },
        {
            name: 'Cora Bednar',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Marc Luettgen',
            id: '88',
        },
        {
            name: 'Jeanette Hills',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Brendan Bradtke',
            id: '89',
        },
        {
            name: 'Lorenzo Weber',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Renee Christiansen DVM',
            id: '90',
        },
        {
            name: 'Mr. Desiree Douglas',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Ramona Harvey',
            id: '91',
        },
        {
            name: 'Chad Gerlach',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Elijah Koss',
            id: '92',
        },
        {
            name: 'Morris Hauck',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Shelley Rodriguez',
            id: '93',
        },
        {
            name: 'Brandi Purdy',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Maurice Zemlak',
            id: '94',
        },
        {
            name: 'Sharon Kuphal',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Earl Brekke',
            id: '95',
        },
        {
            name: 'Caleb Johnston',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Tiffany McKenzie',
            id: '96',
        },
        {
            name: 'Jorge Hegmann I',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Emily Bernhard',
            id: '97',
        },
        {
            name: 'Chelsea Walter',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Ms. Perry Prosacco',
            id: '98',
        },
        {
            name: 'Ms. Joshua Lang',
            avatar: 'https://loremflickr.com/640/480/animals',
            alias: 'Kristy Cruickshank',
            id: '99',
        },
    ]),
    loading: false,
};

const contactsGroup = createSlice({
    name: 'contactsGroup',
    initialState,
    reducers: {},
});

export default contactsGroup.reducer;
export const {} = contactsGroup.actions;
